// ISO 8583-1987 Field Specification Table
// Each field defines: name, maxLength, format, type, category

export interface FieldSpec {
    name: string;
    maxLength: number;
    format: 'FIXED' | 'LLVAR' | 'LLLVAR';
    type: 'n' | 'an' | 'ans' | 'b' | 'z' | 'x+n';
    category: 'identification' | 'amount' | 'processing' | 'date_time' | 'reference' | 'network' | 'terminal' | 'security' | 'reserved' | 'private';
    description?: string;
}

// Complete DE 1-128 spec table (ISO 8583-1987)
export const FIELD_SPECS: Record<number, FieldSpec> = {
    1: { name: 'Bitmap (Secondary)', maxLength: 8, format: 'FIXED', type: 'b', category: 'processing', description: 'Indicates presence of fields 65-128' },
    2: { name: 'Primary Account Number (PAN)', maxLength: 19, format: 'LLVAR', type: 'n', category: 'identification', description: 'Card number used in the transaction' },
    3: { name: 'Processing Code', maxLength: 6, format: 'FIXED', type: 'n', category: 'processing', description: '00=Purchase, 01=Cash Advance, 20=Refund, 30=Balance Inquiry' },
    4: { name: 'Amount, Transaction', maxLength: 12, format: 'FIXED', type: 'n', category: 'amount', description: 'Transaction amount in minor units (cents)' },
    5: { name: 'Amount, Settlement', maxLength: 12, format: 'FIXED', type: 'n', category: 'amount' },
    6: { name: 'Amount, Cardholder Billing', maxLength: 12, format: 'FIXED', type: 'n', category: 'amount' },
    7: { name: 'Transmission Date & Time', maxLength: 10, format: 'FIXED', type: 'n', category: 'date_time', description: 'MMDDhhmmss format' },
    8: { name: 'Amount, Cardholder Billing Fee', maxLength: 8, format: 'FIXED', type: 'n', category: 'amount' },
    9: { name: 'Conversion Rate, Settlement', maxLength: 8, format: 'FIXED', type: 'n', category: 'amount' },
    10: { name: 'Conversion Rate, Cardholder Billing', maxLength: 8, format: 'FIXED', type: 'n', category: 'amount' },
    11: { name: 'System Trace Audit Number (STAN)', maxLength: 6, format: 'FIXED', type: 'n', category: 'reference', description: 'Unique trace number for the transaction' },
    12: { name: 'Time, Local Transaction', maxLength: 6, format: 'FIXED', type: 'n', category: 'date_time', description: 'hhmmss format' },
    13: { name: 'Date, Local Transaction', maxLength: 4, format: 'FIXED', type: 'n', category: 'date_time', description: 'MMDD format' },
    14: { name: 'Date, Expiration', maxLength: 4, format: 'FIXED', type: 'n', category: 'date_time', description: 'YYMM format' },
    15: { name: 'Date, Settlement', maxLength: 4, format: 'FIXED', type: 'n', category: 'date_time' },
    16: { name: 'Date, Conversion', maxLength: 4, format: 'FIXED', type: 'n', category: 'date_time' },
    17: { name: 'Date, Capture', maxLength: 4, format: 'FIXED', type: 'n', category: 'date_time' },
    18: { name: 'Merchant Type (MCC)', maxLength: 4, format: 'FIXED', type: 'n', category: 'terminal', description: 'Merchant Category Code (e.g., 5812=Restaurants)' },
    19: { name: 'Acquiring Institution Country Code', maxLength: 3, format: 'FIXED', type: 'n', category: 'network' },
    20: { name: 'PAN Extended Country Code', maxLength: 3, format: 'FIXED', type: 'n', category: 'identification' },
    21: { name: 'Forwarding Institution Country Code', maxLength: 3, format: 'FIXED', type: 'n', category: 'network' },
    22: { name: 'Point-of-Service Entry Mode', maxLength: 3, format: 'FIXED', type: 'n', category: 'terminal', description: '051=Chip, 071=Contactless, 010=Manual' },
    23: { name: 'Card Sequence Number', maxLength: 3, format: 'FIXED', type: 'n', category: 'identification' },
    24: { name: 'Network International ID', maxLength: 3, format: 'FIXED', type: 'n', category: 'network' },
    25: { name: 'Point-of-Service Condition Code', maxLength: 2, format: 'FIXED', type: 'n', category: 'terminal', description: '00=Normal, 08=Mail/Phone' },
    26: { name: 'Point-of-Service Capture Code', maxLength: 2, format: 'FIXED', type: 'n', category: 'terminal' },
    27: { name: 'Authorizing ID Response Length', maxLength: 1, format: 'FIXED', type: 'n', category: 'processing' },
    28: { name: 'Amount, Transaction Fee', maxLength: 9, format: 'FIXED', type: 'x+n', category: 'amount' },
    29: { name: 'Amount, Settlement Fee', maxLength: 9, format: 'FIXED', type: 'x+n', category: 'amount' },
    30: { name: 'Amount, Transaction Processing Fee', maxLength: 9, format: 'FIXED', type: 'x+n', category: 'amount' },
    31: { name: 'Amount, Settlement Processing Fee', maxLength: 9, format: 'FIXED', type: 'x+n', category: 'amount' },
    32: { name: 'Acquiring Institution ID', maxLength: 11, format: 'LLVAR', type: 'n', category: 'network', description: 'ID of the acquirer bank' },
    33: { name: 'Forwarding Institution ID', maxLength: 11, format: 'LLVAR', type: 'n', category: 'network' },
    34: { name: 'PAN Extended', maxLength: 28, format: 'LLVAR', type: 'ans', category: 'identification' },
    35: { name: 'Track 2 Data', maxLength: 37, format: 'LLVAR', type: 'z', category: 'identification', description: 'Magnetic stripe track 2 equivalent data' },
    36: { name: 'Track 3 Data', maxLength: 104, format: 'LLLVAR', type: 'z', category: 'identification' },
    37: { name: 'Retrieval Reference Number', maxLength: 12, format: 'FIXED', type: 'an', category: 'reference', description: 'Used to match request/response pairs' },
    38: { name: 'Authorization ID Response', maxLength: 6, format: 'FIXED', type: 'an', category: 'reference', description: 'Approval code from issuer' },
    39: { name: 'Response Code', maxLength: 2, format: 'FIXED', type: 'an', category: 'processing', description: '00=Approved, 05=Do Not Honor, 51=Insufficient Funds' },
    40: { name: 'Service Restriction Code', maxLength: 3, format: 'FIXED', type: 'an', category: 'processing' },
    41: { name: 'Card Acceptor Terminal ID', maxLength: 8, format: 'FIXED', type: 'ans', category: 'terminal', description: 'Unique ID of the POS terminal' },
    42: { name: 'Card Acceptor ID Code', maxLength: 15, format: 'FIXED', type: 'ans', category: 'terminal', description: 'Merchant ID' },
    43: { name: 'Card Acceptor Name/Location', maxLength: 40, format: 'FIXED', type: 'ans', category: 'terminal', description: 'Merchant name and location' },
    44: { name: 'Additional Response Data', maxLength: 25, format: 'LLVAR', type: 'an', category: 'processing' },
    45: { name: 'Track 1 Data', maxLength: 76, format: 'LLVAR', type: 'an', category: 'identification' },
    46: { name: 'Additional Data (ISO)', maxLength: 999, format: 'LLLVAR', type: 'an', category: 'processing' },
    47: { name: 'Additional Data (National)', maxLength: 999, format: 'LLLVAR', type: 'an', category: 'processing' },
    48: { name: 'Additional Data (Private)', maxLength: 999, format: 'LLLVAR', type: 'an', category: 'private' },
    49: { name: 'Currency Code, Transaction', maxLength: 3, format: 'FIXED', type: 'n', category: 'amount', description: 'ISO 4217: 840=USD, 978=EUR, 356=INR' },
    50: { name: 'Currency Code, Settlement', maxLength: 3, format: 'FIXED', type: 'n', category: 'amount' },
    51: { name: 'Currency Code, Cardholder Billing', maxLength: 3, format: 'FIXED', type: 'n', category: 'amount' },
    52: { name: 'PIN Data', maxLength: 8, format: 'FIXED', type: 'b', category: 'security', description: 'Encrypted PIN block' },
    53: { name: 'Security Related Control Info', maxLength: 16, format: 'FIXED', type: 'n', category: 'security' },
    54: { name: 'Additional Amounts', maxLength: 120, format: 'LLLVAR', type: 'an', category: 'amount' },
    55: { name: 'ICC/EMV Data', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'security', description: 'Chip card data (TLV format)' },
    56: { name: 'Reserved (ISO)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    57: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    58: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    59: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    60: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    61: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    62: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    63: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    64: { name: 'Message Authentication Code (MAC)', maxLength: 8, format: 'FIXED', type: 'b', category: 'security' },
    // Secondary bitmap fields 65-128
    65: { name: 'Bitmap (Tertiary)', maxLength: 8, format: 'FIXED', type: 'b', category: 'processing' },
    66: { name: 'Settlement Code', maxLength: 1, format: 'FIXED', type: 'n', category: 'processing' },
    67: { name: 'Extended Payment Code', maxLength: 2, format: 'FIXED', type: 'n', category: 'processing' },
    68: { name: 'Receiving Institution Country Code', maxLength: 3, format: 'FIXED', type: 'n', category: 'network' },
    69: { name: 'Settlement Institution Country Code', maxLength: 3, format: 'FIXED', type: 'n', category: 'network' },
    70: { name: 'Network Management Info Code', maxLength: 3, format: 'FIXED', type: 'n', category: 'network', description: '001=Sign-on, 002=Sign-off, 301=Echo Test' },
    71: { name: 'Message Number', maxLength: 4, format: 'FIXED', type: 'n', category: 'reference' },
    72: { name: 'Message Number Last', maxLength: 4, format: 'FIXED', type: 'n', category: 'reference' },
    73: { name: 'Date, Action', maxLength: 6, format: 'FIXED', type: 'n', category: 'date_time' },
    74: { name: 'Credits, Number', maxLength: 10, format: 'FIXED', type: 'n', category: 'amount' },
    75: { name: 'Credits, Reversal Number', maxLength: 10, format: 'FIXED', type: 'n', category: 'amount' },
    76: { name: 'Debits, Number', maxLength: 10, format: 'FIXED', type: 'n', category: 'amount' },
    77: { name: 'Debits, Reversal Number', maxLength: 10, format: 'FIXED', type: 'n', category: 'amount' },
    78: { name: 'Transfer Number', maxLength: 10, format: 'FIXED', type: 'n', category: 'amount' },
    79: { name: 'Transfer, Reversal Number', maxLength: 10, format: 'FIXED', type: 'n', category: 'amount' },
    80: { name: 'Inquiries Number', maxLength: 10, format: 'FIXED', type: 'n', category: 'amount' },
    81: { name: 'Authorizations, Number', maxLength: 10, format: 'FIXED', type: 'n', category: 'amount' },
    82: { name: 'Credits, Processing Fee Amount', maxLength: 12, format: 'FIXED', type: 'n', category: 'amount' },
    83: { name: 'Credits, Transaction Fee Amount', maxLength: 12, format: 'FIXED', type: 'n', category: 'amount' },
    84: { name: 'Debits, Processing Fee Amount', maxLength: 12, format: 'FIXED', type: 'n', category: 'amount' },
    85: { name: 'Debits, Transaction Fee Amount', maxLength: 12, format: 'FIXED', type: 'n', category: 'amount' },
    86: { name: 'Credits, Amount', maxLength: 16, format: 'FIXED', type: 'n', category: 'amount' },
    87: { name: 'Credits, Reversal Amount', maxLength: 16, format: 'FIXED', type: 'n', category: 'amount' },
    88: { name: 'Debits, Amount', maxLength: 16, format: 'FIXED', type: 'n', category: 'amount' },
    89: { name: 'Debits, Reversal Amount', maxLength: 16, format: 'FIXED', type: 'n', category: 'amount' },
    90: { name: 'Original Data Elements', maxLength: 42, format: 'FIXED', type: 'n', category: 'reference', description: 'Used in reversals to reference the original transaction' },
    91: { name: 'File Update Code', maxLength: 1, format: 'FIXED', type: 'an', category: 'processing' },
    92: { name: 'File Security Code', maxLength: 2, format: 'FIXED', type: 'an', category: 'security' },
    93: { name: 'Response Indicator', maxLength: 5, format: 'FIXED', type: 'an', category: 'processing' },
    94: { name: 'Service Indicator', maxLength: 7, format: 'FIXED', type: 'an', category: 'processing' },
    95: { name: 'Replacement Amounts', maxLength: 42, format: 'FIXED', type: 'an', category: 'amount' },
    96: { name: 'Message Security Code', maxLength: 8, format: 'FIXED', type: 'b', category: 'security' },
    97: { name: 'Amount, Net Settlement', maxLength: 17, format: 'FIXED', type: 'x+n', category: 'amount' },
    98: { name: 'Payee', maxLength: 25, format: 'FIXED', type: 'ans', category: 'identification' },
    99: { name: 'Settlement Institution ID', maxLength: 11, format: 'LLVAR', type: 'n', category: 'network' },
    100: { name: 'Receiving Institution ID', maxLength: 11, format: 'LLVAR', type: 'n', category: 'network' },
    101: { name: 'File Name', maxLength: 17, format: 'LLVAR', type: 'ans', category: 'processing' },
    102: { name: 'Account Identification 1', maxLength: 28, format: 'LLVAR', type: 'ans', category: 'identification' },
    103: { name: 'Account Identification 2', maxLength: 28, format: 'LLVAR', type: 'ans', category: 'identification' },
    104: { name: 'Transaction Description', maxLength: 100, format: 'LLLVAR', type: 'ans', category: 'processing' },
    105: { name: 'Reserved (ISO)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    106: { name: 'Reserved (ISO)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    107: { name: 'Reserved (ISO)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    108: { name: 'Reserved (ISO)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    109: { name: 'Reserved (ISO)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    110: { name: 'Reserved (ISO)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    111: { name: 'Reserved (ISO)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    112: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    113: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    114: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    115: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    116: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    117: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    118: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    119: { name: 'Reserved (National)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'reserved' },
    120: { name: 'Record Data', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    121: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    122: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    123: { name: 'POS Data Code', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'terminal' },
    124: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    125: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    126: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    127: { name: 'Reserved (Private)', maxLength: 999, format: 'LLLVAR', type: 'ans', category: 'private' },
    128: { name: 'Message Authentication Code (MAC-2)', maxLength: 8, format: 'FIXED', type: 'b', category: 'security' },
};

// MTI Lookup Tables
export const MTI_VERSION: Record<string, string> = {
    '0': 'ISO 8583:1987',
    '1': 'ISO 8583:1993',
    '2': 'ISO 8583:2003',
    '9': 'Private',
};

export const MTI_CLASS: Record<string, string> = {
    '1': 'Authorization',
    '2': 'Financial',
    '3': 'File Action',
    '4': 'Reversal/Chargeback',
    '5': 'Reconciliation',
    '6': 'Administrative',
    '7': 'Fee Collection',
    '8': 'Network Management',
    '9': 'Reserved',
};

export const MTI_FUNCTION: Record<string, string> = {
    '0': 'Request',
    '1': 'Response',
    '2': 'Advice',
    '3': 'Advice Response',
    '4': 'Notification',
    '5': 'Notification Ack',
    '8': 'Response Ack',
    '9': 'Negative Ack',
};

export const MTI_ORIGIN: Record<string, string> = {
    '0': 'Acquirer',
    '1': 'Acquirer Repeat',
    '2': 'Issuer',
    '3': 'Issuer Repeat',
    '4': 'Other',
    '5': 'Other Repeat',
};

// Well-known MTI descriptions
export const MTI_DESCRIPTIONS: Record<string, string> = {
    '0100': 'Authorization Request — "Can I spend this amount?"',
    '0110': 'Authorization Response — "Yes/No from the issuer"',
    '0120': 'Authorization Advice — Notifying after approval',
    '0200': 'Financial Transaction Request — Capture/Purchase',
    '0210': 'Financial Transaction Response',
    '0220': 'Financial Advice (Completion)',
    '0400': 'Reversal Request — "Undo the last transaction"',
    '0410': 'Reversal Response',
    '0420': 'Reversal Advice — "Force-undo (Ctrl+Z of payments)"',
    '0430': 'Reversal Advice Response',
    '0500': 'Reconciliation Request — "Let\'s settle up"',
    '0510': 'Reconciliation Response',
    '0800': 'Network Management Request — "Are you alive? (Echo/Sign-on)"',
    '0810': 'Network Management Response — "Yes, I\'m here"',
};

// Processing Code descriptions
export const PROCESSING_CODES: Record<string, string> = {
    '00': 'Purchase / Goods & Services',
    '01': 'Cash Advance / Withdrawal',
    '02': 'Debit Adjustment',
    '09': 'Purchase with Cashback',
    '20': 'Refund / Return',
    '22': 'Credit Adjustment',
    '30': 'Balance Inquiry',
    '31': 'Balance Inquiry (Savings)',
    '40': 'Account Transfer',
    '50': 'Payment',
    '90': 'PIN Change',
};

// Response Code descriptions
export const RESPONSE_CODES: Record<string, { text: string; severity: 'success' | 'warning' | 'error' }> = {
    '00': { text: 'Approved', severity: 'success' },
    '01': { text: 'Refer to Card Issuer', severity: 'warning' },
    '02': { text: 'Refer to Card Issuer (Special)', severity: 'warning' },
    '03': { text: 'Invalid Merchant', severity: 'error' },
    '04': { text: 'Pick Up (Capture Card)', severity: 'error' },
    '05': { text: 'Do Not Honor', severity: 'error' },
    '06': { text: 'Error', severity: 'error' },
    '08': { text: 'Approved with ID', severity: 'success' },
    '10': { text: 'Approved (Partial)', severity: 'success' },
    '12': { text: 'Invalid Transaction', severity: 'error' },
    '13': { text: 'Invalid Amount', severity: 'error' },
    '14': { text: 'Invalid Card Number', severity: 'error' },
    '15': { text: 'No Such Issuer', severity: 'error' },
    '19': { text: 'Re-enter Transaction', severity: 'warning' },
    '25': { text: 'Unable to Locate Record', severity: 'error' },
    '30': { text: 'Format Error', severity: 'error' },
    '33': { text: 'Expired Card', severity: 'error' },
    '34': { text: 'Suspected Fraud', severity: 'error' },
    '36': { text: 'Restricted Card', severity: 'error' },
    '41': { text: 'Lost Card', severity: 'error' },
    '43': { text: 'Stolen Card', severity: 'error' },
    '51': { text: 'Insufficient Funds', severity: 'error' },
    '54': { text: 'Expired Card', severity: 'error' },
    '55': { text: 'Incorrect PIN', severity: 'error' },
    '57': { text: 'Transaction Not Allowed', severity: 'error' },
    '58': { text: 'Transaction Not Allowed (Terminal)', severity: 'error' },
    '61': { text: 'Exceeds Withdrawal Limit', severity: 'error' },
    '62': { text: 'Restricted Card', severity: 'error' },
    '63': { text: 'Security Violation', severity: 'error' },
    '65': { text: 'Exceeds Withdrawal Frequency', severity: 'error' },
    '75': { text: 'PIN Tries Exceeded', severity: 'error' },
    '78': { text: 'Blocked (First Use)', severity: 'error' },
    '80': { text: 'Invalid Date', severity: 'error' },
    '82': { text: 'CVV Validation Error', severity: 'error' },
    '85': { text: 'No Reason to Decline (AVS)', severity: 'success' },
    '86': { text: 'Cannot Verify PIN', severity: 'error' },
    '91': { text: 'Issuer Unavailable', severity: 'error' },
    '92': { text: 'Unable to Route', severity: 'error' },
    '94': { text: 'Duplicate Transaction', severity: 'error' },
    '96': { text: 'System Malfunction', severity: 'error' },
};

// ISO 4217 Currency Codes
export const CURRENCY_CODES: Record<string, string> = {
    '036': 'AUD — Australian Dollar',
    '124': 'CAD — Canadian Dollar',
    '156': 'CNY — Chinese Yuan',
    '250': 'FRF — French Franc (legacy)',
    '276': 'DEM — Deutsche Mark (legacy)',
    '344': 'HKD — Hong Kong Dollar',
    '356': 'INR — Indian Rupee',
    '360': 'IDR — Indonesian Rupiah',
    '392': 'JPY — Japanese Yen',
    '410': 'KRW — South Korean Won',
    '458': 'MYR — Malaysian Ringgit',
    '484': 'MXN — Mexican Peso',
    '554': 'NZD — New Zealand Dollar',
    '578': 'NOK — Norwegian Krone',
    '608': 'PHP — Philippine Peso',
    '634': 'QAR — Qatari Riyal',
    '643': 'RUB — Russian Ruble',
    '682': 'SAR — Saudi Riyal',
    '702': 'SGD — Singapore Dollar',
    '710': 'ZAR — South African Rand',
    '752': 'SEK — Swedish Krona',
    '756': 'CHF — Swiss Franc',
    '764': 'THB — Thai Baht',
    '784': 'AED — UAE Dirham',
    '826': 'GBP — British Pound',
    '840': 'USD — US Dollar',
    '978': 'EUR — Euro',
    '986': 'BRL — Brazilian Real',
};
