// Auto-generated from monobank_api (ISO 18245 MCC database, 1088 codes)
// Source: https://github.com/mamantoha/monobank_api + https://github.com/maximbilan/mcc
export const MCC_DATABASE: Record<string, { desc: string; group: string; groupLabel: string }> = {
  '0742': { desc: 'Veterinary Services', group: 'AS', groupLabel: 'Agricultural Services' },
  '0743': { desc: 'Wine producers', group: 'AS', groupLabel: 'Agricultural Services' },
  '0744': { desc: 'Champagne producers', group: 'AS', groupLabel: 'Agricultural Services' },
  '0763': { desc: 'Agricultural Co-operatives', group: 'AS', groupLabel: 'Agricultural Services' },
  '0780': { desc: 'Horticultural and landscaping', group: 'AS', groupLabel: 'Agricultural Services' },
  '1520': { desc: 'General Contractors', group: 'CS', groupLabel: 'Contract services' },
  '1711': { desc: 'Heating, Plumbing, A/C', group: 'CS', groupLabel: 'Contract services' },
  '1731': { desc: 'Electrical Contractors', group: 'CS', groupLabel: 'Contract services' },
  '1740': { desc: 'Masonry, Stonework, and Plaster', group: 'CS', groupLabel: 'Contract services' },
  '1750': { desc: 'Carpentry Contractors', group: 'CS', groupLabel: 'Contract services' },
  '1761': { desc: 'Roofing/Siding, Sheet Metal', group: 'CS', groupLabel: 'Contract services' },
  '1771': { desc: 'Concrete Work Contractors', group: 'CS', groupLabel: 'Contract services' },
  '1799': { desc: 'Special Trade Contractors', group: 'CS', groupLabel: 'Contract services' },
  '2741': { desc: 'Miscellaneous Publishing and Printing', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '2744': { desc: 'Miscellaneous Publishing and Printing', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '2791': { desc: 'Typesetting, Plate Making', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '2842': { desc: 'Specialty Cleaning', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '3000': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3001': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3002': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3003': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3004': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3005': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3006': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3007': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3008': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3009': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3010': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3011': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3012': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3013': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3014': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3015': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3016': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3017': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3018': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3019': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3020': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3021': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3022': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3023': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3024': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3025': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3026': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3027': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3028': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3029': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3030': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3031': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3032': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3033': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3034': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3035': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3036': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3037': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3038': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3039': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3040': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3041': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3042': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3043': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3044': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3045': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3046': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3047': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3048': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3049': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3050': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3051': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3052': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3053': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3054': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3055': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3056': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3057': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3058': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3059': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3060': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3061': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3062': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3063': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3064': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3065': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3066': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3067': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3068': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3069': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3070': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3071': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3072': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3073': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3074': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3075': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3076': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3077': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3078': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3079': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3080': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3081': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3082': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3083': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3084': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3085': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3086': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3087': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3088': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3089': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3090': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3091': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3092': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3093': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3094': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3095': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3096': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3097': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3098': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3099': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3100': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3101': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3102': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3103': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3104': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3105': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3106': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3107': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3108': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3109': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3110': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3111': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3112': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3113': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3114': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3115': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3116': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3117': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3118': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3119': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3120': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3121': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3122': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3123': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3124': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3125': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3126': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3127': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3128': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3129': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3130': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3131': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3132': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3133': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3134': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3135': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3136': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3137': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3138': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3139': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3140': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3141': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3142': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3143': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3144': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3145': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3146': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3147': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3148': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3149': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3150': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3151': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3152': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3153': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3154': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3155': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3156': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3157': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3158': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3159': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3160': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3161': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3162': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3163': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3164': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3165': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3166': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3167': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3168': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3169': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3170': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3171': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3172': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3173': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3174': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3175': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3176': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3177': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3178': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3179': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3180': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3181': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3182': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3183': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3184': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3185': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3186': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3187': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3188': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3189': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3190': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3191': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3192': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3193': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3194': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3195': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3196': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3197': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3198': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3199': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3200': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3201': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3202': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3203': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3204': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3205': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3206': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3207': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3208': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3209': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3210': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3211': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3212': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3213': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3214': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3215': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3216': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3217': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3218': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3219': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3220': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3221': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3222': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3223': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3224': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3225': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3226': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3227': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3228': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3229': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3230': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3231': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3232': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3233': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3234': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3235': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3236': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3237': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3238': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3239': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3240': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3241': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3242': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3243': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3244': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3245': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3246': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3247': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3248': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3249': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3250': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3251': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3252': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3253': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3254': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3255': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3256': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3257': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3258': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3259': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3260': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3261': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3262': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3263': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3264': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3265': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3266': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3267': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3268': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3269': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3270': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3271': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3272': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3273': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3274': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3275': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3276': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3277': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3278': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3279': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3280': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3281': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3282': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3283': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3284': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3285': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3286': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3287': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3288': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3289': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3290': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3291': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3292': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3293': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3294': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3295': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3296': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3297': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3298': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3299': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3300': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3301': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3302': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '3351': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3352': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3353': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3354': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3355': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3356': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3357': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3358': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3359': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3360': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3361': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3362': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3363': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3364': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3365': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3366': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3367': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3368': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3369': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3370': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3371': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3372': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3373': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3374': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3375': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3376': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3377': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3378': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3379': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3380': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3381': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3382': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3383': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3384': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3385': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3386': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3387': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3388': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3389': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3390': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3391': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3392': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3393': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3394': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3395': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3396': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3397': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3398': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3399': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3400': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3401': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3402': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3403': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3404': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3405': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3406': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3407': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3408': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3409': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3410': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3411': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3412': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3413': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3414': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3415': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3416': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3417': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3418': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3419': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3420': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3421': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3422': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3423': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3424': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3425': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3426': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3427': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3428': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3429': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3430': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3431': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3432': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3433': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3434': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3435': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3436': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3437': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3438': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3439': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3440': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3441': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '3501': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3502': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3503': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3504': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3505': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3506': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3507': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3508': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3509': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3510': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3511': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3512': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3513': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3514': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3515': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3516': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3517': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3518': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3519': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3520': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3521': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3522': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3523': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3524': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3525': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3526': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3527': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3528': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3529': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3530': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3531': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3532': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3533': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3534': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3535': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3536': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3537': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3538': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3539': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3540': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3541': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3542': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3543': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3544': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3545': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3546': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3547': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3548': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3549': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3550': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3551': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3552': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3553': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3554': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3555': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3556': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3557': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3558': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3559': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3560': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3561': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3562': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3563': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3564': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3565': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3566': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3567': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3568': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3569': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3570': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3571': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3572': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3573': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3574': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3575': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3576': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3577': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3578': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3579': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3580': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3581': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3582': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3583': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3584': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3585': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3586': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3587': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3588': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3589': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3590': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3591': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3592': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3593': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3594': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3595': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3596': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3597': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3598': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3599': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3600': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3601': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3602': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3603': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3604': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3605': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3606': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3607': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3608': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3609': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3610': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3611': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3612': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3613': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3614': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3615': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3616': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3617': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3618': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3619': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3620': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3621': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3622': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3623': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3624': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3625': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3626': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3627': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3628': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3629': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3630': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3631': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3632': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3633': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3634': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3635': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3636': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3637': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3638': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3639': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3640': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3641': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3642': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3643': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3644': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3645': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3646': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3647': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3648': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3649': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3650': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3651': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3652': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3653': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3654': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3655': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3656': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3657': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3658': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3659': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3660': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3661': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3662': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3663': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3664': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3665': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3666': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3667': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3668': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3669': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3670': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3671': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3672': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3673': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3674': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3675': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3676': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3677': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3678': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3679': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3680': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3681': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3682': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3683': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3684': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3685': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3686': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3687': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3688': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3689': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3690': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3691': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3692': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3693': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3694': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3695': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3696': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3697': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3698': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3699': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3700': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3701': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3702': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3703': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3704': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3705': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3706': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3707': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3708': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3709': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3710': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3711': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3712': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3713': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3714': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3715': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3716': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3717': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3718': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3719': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3720': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3721': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3722': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3723': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3724': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3725': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3726': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3727': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3728': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3729': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3730': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3731': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3732': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3733': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3734': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3735': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3736': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3737': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3738': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3739': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3740': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3741': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3742': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3743': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3744': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3745': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3746': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3747': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3748': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3749': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3750': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3751': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3752': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3753': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3754': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3755': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3756': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3757': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3758': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3759': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3760': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3761': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3762': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3763': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3764': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3765': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3766': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3767': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3768': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3769': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3770': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3771': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3772': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3773': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3774': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3775': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3776': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3777': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3778': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3779': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3780': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3781': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3782': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3783': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3784': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3785': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3786': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3787': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3788': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3789': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3790': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3791': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3792': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3793': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3794': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3795': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3796': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3797': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3798': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3799': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3800': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3801': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3802': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3803': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3804': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3805': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3806': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3807': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3808': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3809': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3810': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3811': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3812': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3813': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3814': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3815': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3816': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3817': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3818': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3819': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3820': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3821': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3822': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3823': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3824': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3825': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3826': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3827': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3828': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3829': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3830': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3831': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3832': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3833': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3834': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3835': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3836': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3837': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3838': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '3882': { desc: 'Сashing', group: 'NC', groupLabel: 'Not categorized' },
  '4011': { desc: 'Railway', group: 'TS', groupLabel: 'Transportation Services' },
  '4111': { desc: 'Passenger transportation', group: 'TS', groupLabel: 'Transportation Services' },
  '4112': { desc: 'Passenger railways', group: 'TS', groupLabel: 'Transportation Services' },
  '4119': { desc: 'Ambulance', group: 'TS', groupLabel: 'Transportation Services' },
  '4121': { desc: 'Taxi', group: 'TS', groupLabel: 'Transportation Services' },
  '4131': { desc: 'Transportation. Bus', group: 'TS', groupLabel: 'Transportation Services' },
  '4214': { desc: 'Transportation. Delivery', group: 'TS', groupLabel: 'Transportation Services' },
  '4215': { desc: 'Delivery service', group: 'TS', groupLabel: 'Transportation Services' },
  '4225': { desc: 'Storage', group: 'TS', groupLabel: 'Transportation Services' },
  '4304': { desc: 'Miscellaneous', group: 'NC', groupLabel: 'Not categorized' },
  '4411': { desc: 'Cruise Lines', group: 'TS', groupLabel: 'Transportation Services' },
  '4457': { desc: 'Boat Rentals', group: 'TS', groupLabel: 'Transportation Services' },
  '4468': { desc: 'Yachting service', group: 'TS', groupLabel: 'Transportation Services' },
  '4511': { desc: 'Airlines', group: 'AL', groupLabel: 'Airlines' },
  '4582': { desc: 'Airports', group: 'TS', groupLabel: 'Transportation Services' },
  '4722': { desc: 'Tourism', group: 'TS', groupLabel: 'Transportation Services' },
  '4723': { desc: 'Tour operators', group: 'TS', groupLabel: 'Transportation Services' },
  '4729': { desc: 'Transportation Services', group: 'TS', groupLabel: 'Transportation Services' },
  '4761': { desc: 'Telemarketing', group: 'TS', groupLabel: 'Transportation Services' },
  '4784': { desc: 'Toll roads', group: 'TS', groupLabel: 'Transportation Services' },
  '4785': { desc: 'Miscellaneous', group: 'NC', groupLabel: 'Not categorized' },
  '4789': { desc: 'Railway', group: 'TS', groupLabel: 'Transportation Services' },
  '4812': { desc: 'Telecommunication equipment', group: 'US', groupLabel: 'Utility Services' },
  '4813': { desc: 'Retail outlets with telephony', group: 'US', groupLabel: 'Utility Services' },
  '4814': { desc: 'Mobile connection', group: 'US', groupLabel: 'Utility Services' },
  '4815': { desc: 'Telephone services', group: 'US', groupLabel: 'Utility Services' },
  '4816': { desc: 'Information Services', group: 'US', groupLabel: 'Utility Services' },
  '4821': { desc: 'Telegraph', group: 'US', groupLabel: 'Utility Services' },
  '4829': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '4899': { desc: 'The television', group: 'US', groupLabel: 'Utility Services' },
  '4900': { desc: 'Utilities', group: 'US', groupLabel: 'Utility Services' },
  '5013': { desc: 'Auto Parts', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5021': { desc: 'Furniture', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5039': { desc: 'Building materials', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5044': { desc: 'Office equipment', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5045': { desc: 'Computers and software', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5046': { desc: 'Equipment', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5047': { desc: 'Medical equipment', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5051': { desc: 'Metal processing', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5065': { desc: 'Electronics', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5072': { desc: 'Equipment', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5074': { desc: 'Plumbing', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5085': { desc: 'Industry', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5094': { desc: 'Jewelry', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5099': { desc: 'Goods', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5111': { desc: 'Chancery', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5122': { desc: 'Drugs', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5131': { desc: 'Haberdashery', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5137': { desc: 'Clothing', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5139': { desc: 'Footwear', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5169': { desc: 'Chemicals', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5172': { desc: 'Petroleum', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5192': { desc: 'Books. Press', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5193': { desc: 'Flowers', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5198': { desc: 'Paints', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5199': { desc: 'Goods', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5200': { desc: 'Household products', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5211': { desc: 'Building materials', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5231': { desc: 'Renovation', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5251': { desc: 'Hardware Stores', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5261': { desc: 'Garden accessories', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5262': { desc: 'Marketplaces', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5271': { desc: 'Mobile homes', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5292': { desc: 'Miscellaneous', group: 'NC', groupLabel: 'Not categorized' },
  '5295': { desc: 'Miscellaneous', group: 'NC', groupLabel: 'Not categorized' },
  '5297': { desc: 'Retail stores', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5298': { desc: 'Retail stores', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5299': { desc: 'Gas sales', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5300': { desc: 'Wholesalers', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5309': { desc: 'Duty Free', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5310': { desc: 'Discounters', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5311': { desc: 'Department stores', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5331': { desc: 'Variety stores', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5399': { desc: 'Merchandise stores', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5411': { desc: 'Grocery', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5415': { desc: 'Miscellaneous', group: 'NC', groupLabel: 'Not categorized' },
  '5422': { desc: 'Meat', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5441': { desc: 'Sweets', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5451': { desc: 'Farm goods', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5462': { desc: 'Bakeries', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5499': { desc: 'Food stores', group: 'ROS', groupLabel: 'Retail Outlet Services' },
  '5511': { desc: 'Car dealerships', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5521': { desc: 'Car dealerships', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5531': { desc: 'Auto parts', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5532': { desc: 'Tires', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5533': { desc: 'Auto shops', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5541': { desc: 'Service Stations', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5542': { desc: 'Gas station', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5551': { desc: 'Boats', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5552': { desc: 'Charging stations', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5561': { desc: 'Car dealerships', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5571': { desc: 'Car dealerships', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5592': { desc: 'Car dealerships', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5598': { desc: 'Car dealerships', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5599': { desc: 'Car dealerships', group: 'CV', groupLabel: 'Cars and vehicles' },
  '5611': { desc: 'Mens clothing', group: 'CLS', groupLabel: 'Clothing stores' },
  '5621': { desc: 'Womens clothing', group: 'CLS', groupLabel: 'Clothing stores' },
  '5631': { desc: 'Clothing stores', group: 'CLS', groupLabel: 'Clothing stores' },
  '5641': { desc: 'Baby clothes', group: 'CLS', groupLabel: 'Clothing stores' },
  '5651': { desc: 'Clothes', group: 'CLS', groupLabel: 'Clothing stores' },
  '5655': { desc: 'Sportswear', group: 'CLS', groupLabel: 'Clothing stores' },
  '5661': { desc: 'Shoes', group: 'CLS', groupLabel: 'Clothing stores' },
  '5681': { desc: 'Fur', group: 'CLS', groupLabel: 'Clothing stores' },
  '5691': { desc: 'Clothes', group: 'CLS', groupLabel: 'Clothing stores' },
  '5697': { desc: 'Atelier', group: 'CLS', groupLabel: 'Clothing stores' },
  '5698': { desc: 'Wigs', group: 'CLS', groupLabel: 'Clothing stores' },
  '5699': { desc: 'Accessories', group: 'CLS', groupLabel: 'Clothing stores' },
  '5712': { desc: 'Furniture', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5713': { desc: 'Floor coverings', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5714': { desc: 'Curtains', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5715': { desc: 'Alcohol', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '5718': { desc: 'Fireplaces', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5719': { desc: 'Furniture', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5722': { desc: 'Household appliance', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5732': { desc: 'Household appliance', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5733': { desc: 'Musical Instruments', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5734': { desc: 'Computer Software', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5735': { desc: 'Record Shops', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5811': { desc: 'Caterers', group: 'SP', groupLabel: 'Service provider' },
  '5812': { desc: 'Cafe. Restaurants', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5813': { desc: 'Bars', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5814': { desc: 'Fast Food', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5815': { desc: 'Digital Goods', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5816': { desc: 'Games', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5817': { desc: 'Applications', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5818': { desc: 'Digital Goods', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5832': { desc: 'Antiques', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5912': { desc: 'Drug Stores', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5921': { desc: 'Alcohol', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5931': { desc: 'Second Hand', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5932': { desc: 'Antiques', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5933': { desc: 'Pawn Shops', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5935': { desc: 'Car dump', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5937': { desc: 'Reproduction Stores', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5940': { desc: 'Bicycles', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5941': { desc: 'Sports goods', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5942': { desc: 'Book Stores', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5943': { desc: 'Stationery', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5944': { desc: 'Clock', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5945': { desc: 'Toys', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5946': { desc: 'Photo goods', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5947': { desc: 'Souvenirs', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5948': { desc: 'Leather Products', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5949': { desc: 'Sewing supplies', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5950': { desc: 'Crystal / glassware', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5960': { desc: 'Insurance', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5961': { desc: 'Goods by mail', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5962': { desc: 'Travels', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5963': { desc: 'Salesmen', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5964': { desc: 'Goods by mail', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5965': { desc: 'Goods by mail', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5966': { desc: 'Goods by mail', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5967': { desc: 'Information Services', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5968': { desc: 'Subscriptions', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5969': { desc: 'Goods by mail', group: 'MTS', groupLabel: 'Mail / Telephone Sales' },
  '5970': { desc: 'Art goods', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5971': { desc: 'Galleries', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5972': { desc: 'Philatelicism', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5973': { desc: 'Church shops', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5974': { desc: 'Rubber stamp', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5975': { desc: 'Hearing Aids', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5976': { desc: 'Prostheses', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5977': { desc: 'Cosmetics', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5978': { desc: 'Printing machines', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5983': { desc: 'Fuel', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5992': { desc: 'Florists', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5993': { desc: 'Tobacco products', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5994': { desc: 'Newspapers. Magazines', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5995': { desc: 'Pet supplies', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5996': { desc: 'Swimming Pools', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5997': { desc: 'Razors', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5998': { desc: 'Tents', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '5999': { desc: 'Miscellaneous', group: 'MS', groupLabel: 'Miscellaneous Stores' },
  '6010': { desc: 'Сashier\'s office', group: 'SP', groupLabel: 'Service provider' },
  '6011': { desc: 'Сashier\'s office', group: 'SP', groupLabel: 'Service provider' },
  '6012': { desc: 'Financial services', group: 'SP', groupLabel: 'Service provider' },
  '6022': { desc: 'Banks', group: 'SP', groupLabel: 'Service provider' },
  '6023': { desc: 'Banks', group: 'SP', groupLabel: 'Service provider' },
  '6025': { desc: 'Banks', group: 'SP', groupLabel: 'Service provider' },
  '6026': { desc: 'Banks', group: 'SP', groupLabel: 'Service provider' },
  '6028': { desc: 'Banks', group: 'SP', groupLabel: 'Service provider' },
  '6050': { desc: 'Quasi Cash', group: 'SP', groupLabel: 'Service provider' },
  '6051': { desc: 'Quasi Cash', group: 'SP', groupLabel: 'Service provider' },
  '6211': { desc: 'Securities', group: 'SP', groupLabel: 'Service provider' },
  '6236': { desc: 'Securities', group: 'AL', groupLabel: 'Airlines' },
  '6300': { desc: 'Insurance', group: 'SP', groupLabel: 'Service provider' },
  '6381': { desc: 'Insurance', group: 'SP', groupLabel: 'Service provider' },
  '6399': { desc: 'Insurance', group: 'SP', groupLabel: 'Service provider' },
  '6513': { desc: 'Rental Property', group: 'SP', groupLabel: 'Service provider' },
  '6529': { desc: 'Сard replenishment', group: 'SP', groupLabel: 'Service provider' },
  '6530': { desc: 'Сard replenishment', group: 'SP', groupLabel: 'Service provider' },
  '6531': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6532': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6533': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6534': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6535': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6536': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6537': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6538': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6539': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6540': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6611': { desc: 'Money transfer', group: 'SP', groupLabel: 'Service provider' },
  '6760': { desc: 'Bonds', group: 'SP', groupLabel: 'Service provider' },
  '7011': { desc: 'Hotels and resorts', group: 'HR', groupLabel: 'Hotels / Resorts' },
  '7012': { desc: 'Timeshares', group: 'SP', groupLabel: 'Service provider' },
  '7032': { desc: 'Recreation', group: 'SP', groupLabel: 'Service provider' },
  '7033': { desc: 'Campgrounds', group: 'SP', groupLabel: 'Service provider' },
  '7210': { desc: 'Cleaning', group: 'PS', groupLabel: 'Personal services' },
  '7211': { desc: 'Laundry', group: 'PS', groupLabel: 'Personal services' },
  '7216': { desc: 'Dry Cleaners', group: 'PS', groupLabel: 'Personal services' },
  '7217': { desc: 'Cleaning', group: 'PS', groupLabel: 'Personal services' },
  '7221': { desc: 'Photographic Studios', group: 'PS', groupLabel: 'Personal services' },
  '7230': { desc: 'The beauty', group: 'PS', groupLabel: 'Personal services' },
  '7251': { desc: 'Clothing repair', group: 'PS', groupLabel: 'Personal services' },
  '7261': { desc: 'Funeral services', group: 'PS', groupLabel: 'Personal services' },
  '7272': { desc: 'Escort', group: 'PS', groupLabel: 'Personal services' },
  '7273': { desc: 'Dating. Escort', group: 'PS', groupLabel: 'Personal services' },
  '7276': { desc: 'Taxes', group: 'PS', groupLabel: 'Personal services' },
  '7277': { desc: 'Consultation', group: 'PS', groupLabel: 'Personal services' },
  '7278': { desc: 'Shopping', group: 'PS', groupLabel: 'Personal services' },
  '7280': { desc: 'Hospitals', group: 'PS', groupLabel: 'Personal services' },
  '7295': { desc: 'Babysitters', group: 'PS', groupLabel: 'Personal services' },
  '7296': { desc: 'Clothing rental', group: 'PS', groupLabel: 'Personal services' },
  '7297': { desc: 'Massage', group: 'PS', groupLabel: 'Personal services' },
  '7298': { desc: 'Health and beauty', group: 'PS', groupLabel: 'Personal services' },
  '7299': { desc: 'Miscellaneous', group: 'PS', groupLabel: 'Personal services' },
  '7311': { desc: 'Advertising', group: 'BS', groupLabel: 'Business Services' },
  '7321': { desc: 'Credit bureaus', group: 'BS', groupLabel: 'Business Services' },
  '7322': { desc: 'Collection agencies', group: 'BS', groupLabel: 'Business Services' },
  '7332': { desc: 'Copy centers', group: 'BS', groupLabel: 'Business Services' },
  '7333': { desc: 'Photography and art', group: 'BS', groupLabel: 'Business Services' },
  '7338': { desc: 'Copy centers', group: 'BS', groupLabel: 'Business Services' },
  '7339': { desc: 'Stenography', group: 'BS', groupLabel: 'Business Services' },
  '7342': { desc: 'Disinfecting', group: 'BS', groupLabel: 'Business Services' },
  '7349': { desc: 'Cleaning and maintenance', group: 'BS', groupLabel: 'Business Services' },
  '7361': { desc: 'Employment', group: 'BS', groupLabel: 'Business Services' },
  '7372': { desc: 'Programming', group: 'BS', groupLabel: 'Business Services' },
  '7375': { desc: 'Information Services', group: 'BS', groupLabel: 'Business Services' },
  '7379': { desc: 'Computer Repair', group: 'BS', groupLabel: 'Business Services' },
  '7389': { desc: 'Business Services', group: 'BS', groupLabel: 'Business Services' },
  '7392': { desc: 'Consulting, PR', group: 'BS', groupLabel: 'Business Services' },
  '7393': { desc: 'Detective agencies', group: 'BS', groupLabel: 'Business Services' },
  '7394': { desc: 'Equipment rental', group: 'BS', groupLabel: 'Business Services' },
  '7395': { desc: 'Photo printing', group: 'BS', groupLabel: 'Business Services' },
  '7399': { desc: 'Business Services', group: 'BS', groupLabel: 'Business Services' },
  '7511': { desc: 'Parking', group: 'BS', groupLabel: 'Business Services' },
  '7512': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '7513': { desc: 'Truck Rental', group: 'CR', groupLabel: 'Car rent' },
  '7519': { desc: 'Car rent', group: 'CR', groupLabel: 'Car rent' },
  '7523': { desc: 'Parking', group: 'BS', groupLabel: 'Business Services' },
  '7524': { desc: 'Parking', group: 'BS', groupLabel: 'Business Services' },
  '7531': { desc: 'Auto repair', group: 'RS', groupLabel: 'Repair services' },
  '7534': { desc: 'Tire service', group: 'RS', groupLabel: 'Repair services' },
  '7535': { desc: 'Car paints', group: 'RS', groupLabel: 'Repair services' },
  '7538': { desc: 'Maintenance stations', group: 'RS', groupLabel: 'Repair services' },
  '7542': { desc: 'Car Washes', group: 'RS', groupLabel: 'Repair services' },
  '7549': { desc: 'Tow truck', group: 'RS', groupLabel: 'Repair services' },
  '7622': { desc: 'Repair of equipment', group: 'RS', groupLabel: 'Repair services' },
  '7623': { desc: 'HVAC equipment repair', group: 'RS', groupLabel: 'Repair services' },
  '7629': { desc: 'Repair of equipment', group: 'RS', groupLabel: 'Repair services' },
  '7631': { desc: 'Repair of watches and jewelry', group: 'RS', groupLabel: 'Repair services' },
  '7641': { desc: 'Furniture repair', group: 'RS', groupLabel: 'Repair services' },
  '7692': { desc: 'Welding works', group: 'RS', groupLabel: 'Repair services' },
  '7699': { desc: 'Repairs', group: 'RS', groupLabel: 'Repair services' },
  '7800': { desc: 'Government Owned Lottery', group: 'ES', groupLabel: 'Entertainment services' },
  '7801': { desc: 'Online casino', group: 'ES', groupLabel: 'Entertainment services' },
  '7802': { desc: 'Horse / Dog racing', group: 'ES', groupLabel: 'Entertainment services' },
  '7829': { desc: 'Video rental', group: 'ES', groupLabel: 'Entertainment services' },
  '7832': { desc: 'Cinemas', group: 'ES', groupLabel: 'Entertainment services' },
  '7833': { desc: 'Cinemas', group: 'ES', groupLabel: 'Entertainment services' },
  '7841': { desc: 'Video rental', group: 'ES', groupLabel: 'Entertainment services' },
  '7911': { desc: 'Dance studios. Dance schools', group: 'ES', groupLabel: 'Entertainment services' },
  '7922': { desc: 'Tickets', group: 'ES', groupLabel: 'Entertainment services' },
  '7929': { desc: 'Music bands. Orchestras', group: 'ES', groupLabel: 'Entertainment services' },
  '7932': { desc: 'Billiard', group: 'ES', groupLabel: 'Entertainment services' },
  '7933': { desc: 'Bowling clubs', group: 'ES', groupLabel: 'Entertainment services' },
  '7941': { desc: 'Sports clubs', group: 'ES', groupLabel: 'Entertainment services' },
  '7991': { desc: 'Tourism', group: 'ES', groupLabel: 'Entertainment services' },
  '7992': { desc: 'Golf', group: 'ES', groupLabel: 'Entertainment services' },
  '7993': { desc: 'Videogames', group: 'ES', groupLabel: 'Entertainment services' },
  '7994': { desc: 'Videogames', group: 'ES', groupLabel: 'Entertainment services' },
  '7995': { desc: 'Gambling', group: 'ES', groupLabel: 'Entertainment services' },
  '7996': { desc: 'Entertainment', group: 'ES', groupLabel: 'Entertainment services' },
  '7997': { desc: 'Entertainment and sport', group: 'ES', groupLabel: 'Entertainment services' },
  '7998': { desc: 'Aquariums. Dolphinariums', group: 'ES', groupLabel: 'Entertainment services' },
  '7999': { desc: 'Entertainment and sport', group: 'ES', groupLabel: 'Entertainment services' },
  '8011': { desc: 'Medicine', group: 'PFS', groupLabel: 'Professional services' },
  '8021': { desc: 'Dentistry', group: 'PFS', groupLabel: 'Professional services' },
  '8031': { desc: 'Medicine', group: 'PFS', groupLabel: 'Professional services' },
  '8041': { desc: 'Chiropractors', group: 'PFS', groupLabel: 'Professional services' },
  '8042': { desc: 'Optics', group: 'PFS', groupLabel: 'Professional services' },
  '8043': { desc: 'Optics', group: 'PFS', groupLabel: 'Professional services' },
  '8044': { desc: 'Optics', group: 'PFS', groupLabel: 'Professional services' },
  '8049': { desc: 'Podiatrists', group: 'PFS', groupLabel: 'Professional services' },
  '8050': { desc: 'Caregiver / Nurse', group: 'PFS', groupLabel: 'Professional services' },
  '8062': { desc: 'Hospitals', group: 'PFS', groupLabel: 'Professional services' },
  '8071': { desc: 'Medicine and dentistry', group: 'PFS', groupLabel: 'Professional services' },
  '8099': { desc: 'Medical services', group: 'PFS', groupLabel: 'Professional services' },
  '8110': { desc: 'Lawyers', group: 'PFS', groupLabel: 'Professional services' },
  '8111': { desc: 'Lawyers', group: 'PFS', groupLabel: 'Professional services' },
  '8211': { desc: 'School', group: 'PFS', groupLabel: 'Professional services' },
  '8220': { desc: 'Education. University', group: 'PFS', groupLabel: 'Professional services' },
  '8241': { desc: 'Schools, Correspondence', group: 'PFS', groupLabel: 'Professional services' },
  '8244': { desc: 'Education. Business', group: 'PFS', groupLabel: 'Professional services' },
  '8249': { desc: 'Education', group: 'PFS', groupLabel: 'Professional services' },
  '8299': { desc: 'Education', group: 'PFS', groupLabel: 'Professional services' },
  '8351': { desc: 'Kindergarten', group: 'PFS', groupLabel: 'Professional services' },
  '8398': { desc: 'Charity', group: 'MO', groupLabel: 'Membership оrganizations' },
  '8641': { desc: 'Public organizations', group: 'MO', groupLabel: 'Membership оrganizations' },
  '8651': { desc: 'Organizations, Political', group: 'MO', groupLabel: 'Membership оrganizations' },
  '8661': { desc: 'Organizations, Religious', group: 'MO', groupLabel: 'Membership оrganizations' },
  '8664': { desc: 'Miscellaneous', group: 'NC', groupLabel: 'Not categorized' },
  '8675': { desc: 'Autoclub', group: 'MO', groupLabel: 'Membership оrganizations' },
  '8699': { desc: 'Organizations, Membership', group: 'MO', groupLabel: 'Membership оrganizations' },
  '8734': { desc: 'Testing laboratories', group: 'PFS', groupLabel: 'Professional services' },
  '8743': { desc: 'Testing laboratories', group: 'PFS', groupLabel: 'Professional services' },
  '8911': { desc: 'Architects', group: 'PFS', groupLabel: 'Professional services' },
  '8931': { desc: 'Accounting. Audit', group: 'PFS', groupLabel: 'Professional services' },
  '8999': { desc: 'Professional services', group: 'PFS', groupLabel: 'Professional services' },
  '9034': { desc: 'I-Purchasing Pilot', group: 'GS', groupLabel: 'Government Services' },
  '9211': { desc: 'Court', group: 'GS', groupLabel: 'Government Services' },
  '9222': { desc: 'Fines', group: 'GS', groupLabel: 'Government Services' },
  '9223': { desc: 'Payouts. Bonds', group: 'GS', groupLabel: 'Government Services' },
  '9311': { desc: 'Taxes', group: 'GS', groupLabel: 'Government Services' },
  '9399': { desc: 'Government Services', group: 'GS', groupLabel: 'Government Services' },
  '9401': { desc: 'I-Purchasing Pilot', group: 'GS', groupLabel: 'Government Services' },
  '9402': { desc: 'Mail', group: 'GS', groupLabel: 'Government Services' },
  '9405': { desc: 'Government procurement', group: 'GS', groupLabel: 'Government Services' },
  '9406': { desc: 'Government Owned Lottery', group: 'ES', groupLabel: 'Entertainment services' },
  '9411': { desc: 'Government Services', group: 'GS', groupLabel: 'Government Services' },
  '9700': { desc: 'Cashback', group: 'NC', groupLabel: 'Not categorized' },
  '9701': { desc: 'VISA', group: 'NC', groupLabel: 'Not categorized' },
  '9702': { desc: 'Emergency services', group: 'NC', groupLabel: 'Not categorized' },
  '9751': { desc: 'Document flow', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '9752': { desc: 'Document flow', group: 'WSM', groupLabel: 'Wholesale suppliers and manufacturers' },
  '9754': { desc: 'Horse / Dog racing', group: 'GS', groupLabel: 'Government Services' },
  '9950': { desc: 'In-company purchases', group: 'NC', groupLabel: 'Not categorized' },
  '9999': { desc: 'Miscellaneous', group: 'NC', groupLabel: 'Not categorized' },
};

export function getMccDescription(code: string): string | undefined {
  return MCC_DATABASE[code]?.desc;
}

export function getMccGroup(code: string): { type: string; label: string } | undefined {
  const entry = MCC_DATABASE[code];
  return entry ? { type: entry.group, label: entry.groupLabel } : undefined;
}